export class PatientObj { 

    PatientObj()
    {
        this.fullName = "";
        this.fullNameAr = "";
        this.Height = "";
        this.bldGrp = "";
        this.kAllergies = "";
        this.Hospital = "";
        this.contactInfo = "";
        this.Gender = "";
        this.n_ID = "";
        this.Nationality = "";
        this.submittedBy = "";
        this.dosDialysis = "";
        this.oKidneyDisease = "";
        this.otherKD = "";
        this.surgHist1 = "";
        this.surgHist2 = "";
        this.morbHype = false;
        this.morbDM = false;
        this.morbIHD = false;
        this.morbEpi = false;
        this.coMorbOther = "";
        this.previousTr = "";
        this.prevTrGS = "";
        this.fitForTr = "";
        this.fitForTrReason = "";
        this.potentialRDonors = "";
        this.currentAccess1 = "";
        this.currentAccess2 = "";
        this.currentAccess3 = "";
        this.dOfAccessCreation = "";
        this.compInsuf = false;
        this.compInf = false;
        this.compAD = false;
        this.compDC = false;
        this.compOther = "";
        this.previousAccess1 = "";
        this.previousAccess2 = "";
        this.previousAccess3 = "";
        this.previousAccess4 = "";
        this.Frequency = "";
        this.Duration = "";
        this.Dialyser = "";
        this.antiCoagulation = "";
        this.hInit = "";
        this.hMaint = "";
        this.LMWHval = "";
        this.antiCoReason = "";
        this.dryWt = "";
        this.avgWtGain = "";
        this.avgBP = "";
        this.avgPulse = "";
        this.dialAdeq = "";
        this.dCompHead = false;
        this.dCompHG = false;
        this.dCompHOT = false;
        this.dCompHET = false; 
        this.dCompMC = false;
        this.dCompAC = false;
        this.dCompVom = false;
        this.dCompSZ = false;
        this.dCompHS = false;
        this.dCompIt = false;
        this.dCompOther = "";
        this.labDate = "";
        this.cbcHB = "";
        this.cbcWBC = "";
        this.cbcPlatelets = "";
        this.chemCrePre = "";
        this.chemUreaPre = "";
        this.chemCrePost = "";
        this.chemUreaPost = "";
        this.chemSod = "";
        this.chemPot = "";
        this.chemCal = "";
        this.chemPhos = "";
        this.chemAST = "";
        this.chemALT = "";
        this.chemAlb = "";
        this.chemMag = "";
        this.chemAlph = "";
        this.chemOther = "";
        this.Siron = "";
        this.TIBC = "";
        this.Sferitin = "";
        this.hormPTH = "";
        this.hormVITD = "";
        this.hormOther = "";
        this.hbsAg = "";
        this.hcvAb = "";
        this.hivI_II = "";
        this.othrSer = "";
        this.coagPT  = "";
        this.coagPPT  = "";
        this.coagINR = "";
        this.cMD1 = "";
        this.cMD2 = "";
        this.cMD3 = "";
        this.cMD4 = "";
        this.cMD5 = "";
        this.cMD6 = "";
        this.cMD7 = "";
        this.cMD8 = "";
        this.cMD9 = "";
        this.cMD10 = "";
        this.cMD11 = "";
        this.cMD12 = "";
        this.cMD13 = "";
        this.cMD14 = "";
        this.cMD15 = "";
        this.cMD16 = "";
        this.HepBV = "";
        this.HepBVDate = "";
        this.InfV = "";
        this.InfVDate = "";
        this.otherVAC = "";
        this.progNotes = "";
        this.consNotes = "";
        this.Referrals = "";
    }


    
    fullName: String;
    fullNameAr: String;
    Age: String;
    Height:String;
    bldGrp: String;
    kAllergies: String;
    Hospital: String;
    contactInfo: String;
    Gender: String;
    n_ID: String;
    Nationality: String;
    submittedBy: String;
    dosDialysis: String;
    oKidneyDisease: String;
    otherKD: String;
    surgHist1: String;
    surgHist2: String;
    morbHype: boolean;
    morbDM: boolean;
    morbIHD: boolean;
    morbEpi: boolean;
    coMorbOther: String;
    previousTr: String;
    prevTrGS: String;
    fitForTr: String;
    fitForTrReason: String;
    potentialRDonors: String;
    currentAccess1: String;
    currentAccess2: String;
    currentAccess3: String;
    dOfAccessCreation: String;
    compInsuf: boolean;
    compInf: boolean;
    compAD: boolean;
    compDC: boolean;
    compOther: String;
    previousAccess1: String;
    previousAccess2: String;
    previousAccess3: String;
    previousAccess4: String;
    Frequency: String;
    Duration: String;
    Dialyser: String;
    antiCoagulation: String;
    hInit: String;
    hMaint: String;
    LMWHval: String;
    antiCoReason: String;
    dryWt: String;
    avgWtGain: String;
    avgBP: String;
    avgPulse: String;
    dialAdeq: String;
    dCompHead: boolean;
    dCompHG: boolean;
    dCompHOT: boolean;
    dCompHET: boolean;
    dCompMC : boolean;
    dCompAC : boolean;
    dCompVom: boolean;
    dCompSZ: boolean;
    dCompHS: boolean;
    dCompIt: boolean;
    dCompOther: String;
    labDate: String;
    cbcHB: String;
    cbcWBC: String;
    cbcPlatelets: String;
    chemCrePre: String;
    chemUreaPre: String;
    chemCrePost: String;
    chemUreaPost: String;
    chemSod: String;
    chemPot: String;
    chemCal: String;
    chemPhos: String;
    chemAST: String;
    chemALT: String;
    chemAlb: String;
    chemMag: String;
    chemAlph: String;
    chemOther: String;
    Siron: String;
    TIBC: String;
    Sferitin: String;
    TSAT: String;
    hormPTH: String;
    hormVITD: String;
    hormOther: String;
    hbsAg: String;
    hcvAb: String;
    hcvPCR: String;
    hivI_II: String;
    othrSer: String;
    coagPT: String;
    coagPPT: String;
    coagINR: String;
    cMD1: String;
    cMD2: String;
    cMD3: String;
    cMD4: String;
    cMD5: String;
    cMD6: String;
    cMD7: String;
    cMD8: String;
    cMD9: String;
    cMD10: String;
    cMD11: String;
    cMD12: String;
    cMD13: String;
    cMD14: String;
    cMD15: String;
    cMD16: String;
    HepBV: String;
    HepBVDate: String;
    InfV: String;
    InfVDate: String;
    otherVAC: String;
    progNotes: String;
    consNotes: String;
    Referrals: String;


}